[package]
name = "xtee"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "xtee_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

openssl-sys = {version = "0.9", features = ["vendored"] }
tauri-plugin-log = "2"
tauri-plugin-store = "2"
ractor = "0.13.0"
deku = "0.18.1"
crc = "3.2.1"
cobs-codec = "0.1.0"
tokio = "1.41.0"
tokio-util = "0.7.12"
#rppal = "0.19.0"
