// This file was generated by [rspc](https://github.com/specta-rs/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "controllers", input: never, result: Controller[] } | 
        { key: "motor/get/max-speed", input: number, result: number },
    mutations: 
        { key: "actuator/keep", input: number, result: null } | 
        { key: "actuator/load", input: number, result: null } | 
        { key: "actuator/move", input: number, result: null } | 
        { key: "actuator/stop", input: never, result: null } | 
        { key: "motor/keep", input: [number, MotorMovement], result: null } | 
        { key: "motor/set/outputs", input: [number, boolean], result: boolean } | 
        { key: "motor/spin", input: [number, MotorMovement], result: null } | 
        { key: "motor/stop", input: [number, MotorStopMode], result: null } | 
        { key: "restart", input: never, result: null },
    subscriptions: 
        { key: "events", input: never, result: Event }
};

export type Controller = { id: string; group: ControllerGroup; serial_port: string; baud_rate: number }

export type ControllerGroup = "default" | "motors"

export type Event = { type: "weight"; data: number } | { type: "motor-status"; data: MotorStatus }

export type MotorMovement = { speed: number; direction: number; rotations: number }

export type MotorStatus = { status: "idle" } | { status: "stopping" } | { status: "spinning"; data: { position: number; remaining: number } }

export type MotorStopMode = "graceful" | "emergency"
