// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: never,
    mutations: 
        { key: "actuator/keep", input: number, result: null } | 
        { key: "actuator/load", input: number, result: null } | 
        { key: "actuator/move", input: number, result: null } | 
        { key: "actuator/stop", input: never, result: null },
    subscriptions: never
};
